apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: concord-pvc-{{ .Values.global.blockchainId }}-replica-3
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1Gi"